language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 'node'
  - '6'
  - '7'
after_success:
  - "$(npm bin)/coveralls < ./coverage/lcov.info"
  - "$(npm bin)/codeclimate-test-reporter < ./coverage/lcov.info"
