language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - 'node'
  - '6'
after_success:
  - "$(npm bin)/coveralls < ./coverage/lcov.info"
  - "$(npm bin)/codeclimate-test-reporter < ./coverage/lcov.info"
before_deploy:
  - "[ -n \"${TRAVIS_TAG}\" ] && git archive --format tar.gz --prefix=simple-process-${TRAVIS_TAG}/ -o ${HOME}/simple-process-${TRAVIS_TAG}.tar.gz ${TRAVIS_TAG}"
deploy:
  - provider: npm
    skip_cleanup: true
    email: "hiroaki@hysoftware.net"
    api_key:
      secure: >-
        RxXH0gpVyiz0BfySFg2RGK4PPZuPKzcRwmHktYitvdXW9NAuo1BqL/nHtS6QPNxd9JOWnx
        gh8+nIHNkyLW4wgLNztA23PUhSFMYRAu7NQv66YfmamDAywHvRwiq0Dh7gQI9hS6X7t+x3
        EV9opSUqBrBzqSHLgtrVjSnBy4XSY+tu9fl7FkNMH6lnfFfTNAJLDo/QhE3MOEUWc2AXLR
        kIhaKaW+MRKTdk7c1bnhIaJIxZfprFIKLhmfut2qkYb839bgXlusrAbfKdkfp+EHYnRfTa
        +jfJbAmTmx4/NlK+dbMs4u/rj/eYokCq1dtoGkOZSdN6mxGzQzg4xiuRa7xU2LjyyJPjPL
        vS74JzlpM0QaksJqA5AD4Ts1Y1+QU5tpX7UXzsebPBPf+QFixaL4pirZd6cxBg3m1Mgz6b
        tfiPtmRdQl8FzJudr8Uti9V6xlUzdQxMOxkt8nJylgoxhbsFEfzSBVW7lz9xUeyRnLo0S+
        atulJporu2Cd3iA3WxQaaUBSosBhf8DtYBQ9oqeaQ7bUaBPp92MC/VhjPyMFliBVgjD41t
        Yum2L8ow3T10sOAX1EpqefhCRj03FtObkvADzEMt3TQLW9D7rjnuYHkzqWCX1TtSOY8gHd
        5DHIWAFKGLf2ikoejBhbk6agGWuOCAqevblDkKbB9I56woHa4lNAw=
    on:
      tags: true
  - provider: releases
    file: ${HOME}/simple-process-${TRAVIS_TAG}.tar.gz
    skip_cleanup: true
    overwrite: true
    api_key:
      secure: >-
        tEr10/n5teIihmq35MjBZpEqmEvniFm2C4Ua7kctXdpocwF9L35emrMTRaAhaNTB/S4Zyz
        +ZSuBasDaYCjzdWxTrtsDj4ZlTfwKUrR46G9bVLX30nwVEHSYxtnFYWm2CEr3bvyOrEJNd
        SHiy16aCrzSr0Miko5wOjR61aaTebQ1TUp6UWd+E8Nhcl1W290liieL734YE2KV5t4Xybm
        /auYlXIidOlucV2GOtS0jP+Bj98V8j+FQMMZB8YbNJoa5R/6Pk1ZH2D6CBs96OACoZDPCj
        ZKdyv/BdoINZ7l9Vfw+RL7F24GqlCuRmZ4iZyEVf8/+6wcumQjrzJvZrV/tLFLiK+Ku9IH
        lKpVerPegF9AwzY0zyoZJe4y0wL/AdiqoOaYSe7nBfnXvNJFAZAO6+wgUr0JDsYKGWzH3k
        5Ko3JFbNagJEtURwTw2dayoOEDh7wTzSjmA5c446ikzVwB1OLWUNtU92QceQxoN1pfEN1b
        BKtQxliCXiMPjEST00dY0/FH3UWt3e/G5JieAYAkQecIU9zPsRxPfdMS0cpBoRNJQXd4Em
        nm5Fy2I1+HdooCgZvlx/i9xO+dHienpCSEztDw7i8JnPTSH0612nTMXwVbzn15U+u/3lrx
        osISG5GqpqzMzENYr3+MOD+rWGYRzFXPGOhy8kBYVllRnHwkSFWBo=
    on:
      tags: true
